name: CI - Django Tests and Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: alx_db
          MYSQL_ROOT_PASSWORD: alx
          MYSQL_USER: mankindjnr
          MYSQL_PASSWORD: alx
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 coverage

    - name: Wait for Database to Start
      run: |
        until mysqladmin ping -h127.0.0.1 --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Run Flake8 Linting
      run: |
        flake8 .
      continue-on-error: false

    - name: Run Tests with Coverage
      env:
        DATABASE_URL: mysql://mankindjnr:alx@127.0.0.1:5432/alx_db
      run: |
        coverage run --source='.' manage.py test
        coverage report
        coverage xml

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
