name: CI - Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: alx_db
          MYSQL_ROOT_PASSWORD: alx
          MYSQL_USER: mankindjnr
          MYSQL_PASSWORD: alx
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Database to Start
      run: |
        until mysqladmin ping -h127.0.0.1 --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Run Tests
      env:
        DATABASE_URL: mysql://mankinsjnd:alx@127.0.0.1:5432/alx_db
      run: |
        python manage.py test
